# Generated by Django 6.0.1 on 2026-02-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
